services:
  arch-vscode:
    build: .
    container_name: arch-vscode-dev
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - WORKSPACE_DIR=/workspace
      - VSCODE_USER_DATA_DIR=/config/user-data
      - VSCODE_EXTENSIONS_DIR=/config/extensions
      - VSCODE_SERVER_DATA_DIR=/config/server-data
      - AUTO_UPDATE=${AUTO_UPDATE:-false}
      - TZ=${TZ:-UTC}
    volumes:
      - ./:/workspace
      - vscode-config:/config
    ports:
      - "8080:8080"
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    networks:
      - arch-vscode-net

  # Optional: Add a reverse proxy for custom domain access
  # nginx:
  #   image: nginx:alpine
  #   container_name: arch-vscode-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - arch-vscode
  #   restart: unless-stopped
  #   networks:
  #     - arch-vscode-net
  #   profiles:
  #     - proxy

volumes:
  vscode-config:
    driver: local

networks:
  arch-vscode-net:
    driver: bridge