services:
  arch-vscode:
    build: .
    container_name: arch-vscode-dev
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - USERNAME=${USERNAME:-developer}
      - WORKSPACE_DIR=/workspace
      - VSCODE_DEFAULT_FOLDER=${VSCODE_DEFAULT_FOLDER:-/workspace}
      - VSCODE_USER_DATA_DIR=/config/user-data
      - VSCODE_EXTENSIONS_DIR=/config/extensions
      - VSCODE_SERVER_DATA_DIR=/config/server-data
      - EXTRA_PACKAGES=${EXTRA_PACKAGES:-}
      - AUTO_UPDATE=${AUTO_UPDATE:-false}
      - TZ=${TZ:-UTC}
    volumes:
      - ./:/workspace
      - vscode-config:/config
      - home-data:/home
    ports:
      - "8080:8080"
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    networks:
      - arch-vscode-net

volumes:
  vscode-config:
    driver: local
  home-data:
    driver: local