name: Docker Publish

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag for the image'
        required: false
        default: 'latest'

env:
  REGISTRY_DOCKERHUB: docker.io
  REGISTRY_GHCR: ghcr.io
  IMAGE_NAME: jjgroenendijk/arch-vscode

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_DOCKERHUB }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_GHCR }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}
          ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch,enable={{is_default_branch}}
          type=sha,prefix={{branch}}-,enable=${{ github.event_name == 'push' }}
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=latest,enable=${{ github.event_name == 'schedule' }}
          type=raw,value=weekly-{{date 'YYYY-MM-DD'}},enable=${{ github.event_name == 'schedule' }}
          type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event_name == 'workflow_dispatch' }}
        labels: |
          org.opencontainers.image.title=Arch Linux VS Code Container
          org.opencontainers.image.description=Arch Linux container with VS Code accessible via web interface
          org.opencontainers.image.source=https://github.com/jjgroenendijk/arch-vscode
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.vendor=jjgroenendijk

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: true
        sbom: true

    - name: Generate SBOM attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.build.outputs.digest }}

    - name: Test container startup
      run: |
        echo "Testing container startup..."
        docker run --rm --name test-container -d \
          -p 8080:8080 \
          ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}:latest

        sleep 30

        if docker ps | grep -q test-container; then
          echo "Container is running successfully"
        else
          echo "Container failed to start"
          docker logs test-container
          exit 1
        fi

        docker stop test-container
        echo "Container test completed successfully"

    - name: Create build summary
      run: |
        if [ "${{ github.event_name }}" == "schedule" ]; then
          echo "## Weekly Docker Image Rebuild" >> $GITHUB_STEP_SUMMARY
          TRIGGER_TEXT="Weekly scheduled rebuild"
          BASE_IMAGE_TEXT="archlinux:latest (rebuilt weekly)"
        else
          echo "## Docker Image Built and Pushed" >> $GITHUB_STEP_SUMMARY
          TRIGGER_TEXT="Code changes or manual trigger"
          BASE_IMAGE_TEXT="archlinux:latest"
        fi

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Images Published:" >> $GITHUB_STEP_SUMMARY
        echo "- **Docker Hub**: \`docker pull ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
        echo "- **GitHub Container Registry**: \`docker pull ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Quick Start:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "docker run -it --rm -v \$(pwd):/workspace -p 8080:8080 ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Access:" >> $GITHUB_STEP_SUMMARY
        echo "Open [http://localhost:8080](http://localhost:8080) in your browser" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Features:" >> $GITHUB_STEP_SUMMARY
        if [ "${{ github.event_name }}" == "schedule" ]; then
          echo "- **Weekly Rebuild**: Automatically rebuilds with latest packages" >> $GITHUB_STEP_SUMMARY
        fi
        echo "- **Build Provenance**: SBOM and attestations included" >> $GITHUB_STEP_SUMMARY
        echo "- **Multi-Registry**: Available on Docker Hub and GitHub Container Registry" >> $GITHUB_STEP_SUMMARY
        echo "- **Container Tests**: Startup and health checks passed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Build Info:" >> $GITHUB_STEP_SUMMARY
        echo "- **Platform**: linux/amd64" >> $GITHUB_STEP_SUMMARY
        echo "- **Base Image**: $BASE_IMAGE_TEXT" >> $GITHUB_STEP_SUMMARY
        echo "- **VS Code**: Latest stable from Microsoft" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Date**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Trigger**: $TRIGGER_TEXT" >> $GITHUB_STEP_SUMMARY

    - name: Clean up Docker build cache
      if: always() && github.event_name == 'schedule'
      run: |
        echo "Cleaning up Docker build cache..."
        docker builder prune -f
        echo "Build cache cleaned"
